CREATE ROLE "custom2" WITH LOGIN PASSWORD '1753';
GRANT USAGE ON SCHEMA "public" TO "custom2";
GRANT SELECT ON ALL TABLES IN SCHEMA "public" TO "custom2";
CREATE EXTENSION IF NOT EXISTS anon CASCADE;
SELECT anon.start_dynamic_masking();
SECURITY LABEL FOR anon ON ROLE "custom2" IS 'MASKED';